### PR TITLE
Recommendations for a practical conference timeline

### PR DESCRIPTION
**Pull request by skade**
#17

### CODE REVIEW

**Comment by spastorino** [comment]
First of all, this is great!!!

As we are running Rust Latam, I think it could be nice to add a `define a rough estimate of conference costs`, which would involve having a couple of venue prices, food, recording, translations if needed, etc, etc.
So with that info you may know more or less if the thing is viable and/or how much would you need to set the sponsor and tickets prices.

Another thing is that ...
```
## 5 days before

* Communicate diatary restrictions to the caterer

## 4 days before

* Badges go to printer
```

May be too short. It's definitely too short here, small country, third world so it's not that you get this kind of stuff in one day. I'd move to at least 1 month in advance to be 100% sure that you will get the stuff.

**Comment by badboy** [comment]
@spastorino: Especially dates are definitely a thing that varies from location to location. However these are things you can plan for (you just need to clarify it early when the deadline would be).

During `impl Days` @skade gave a workshop for event planning and we're collecting results here: https://github.com/rust-community/foss-events-planner

We plan to extend the issues into a document with a proper timeline and a task list one can work from.

**Comment by spastorino** [comment]
So are those dates seen as deadline? or start of work?, I guess deadlines, in that case it's ok :).

**Comment by badboy** [comment]
Deadlines. That's when it needs to happen.

**Comment by skade** [comment]
Hi @spastorino, thanks for noticing that. Especially the "dietary restrictions" should be "final dietary restrictions".

You can always communicate earlier, but people will fill out their forms until the very last minute, which means you want to find the latest possible date for that. Your supplier will help you in finding that date.

**Comment by spastorino** [comment]
> You can always communicate earlier, but people will fill out their forms until the very last minute, which means you want to find the latest possible date for that. Your supplier will help you in finding that date.

Yes, that's true. I was trying to give some advice about how things may work in the third world. In particular in Uruguay things are probably going to be ok, but doing that here is taking a huge risk ;). Probably better to do an "estimate" of the food and restrictions.

**Comment by skade** [comment]
@spastorino Yeah, we should communicate better that "this deadline should be planned with your supplier".

BTW, we have rust-community/foss-events-planner now, which might help with that in the future.

**Comment by skade** [comment]
@badboy cool, could you open an issue over there then?

**Pull request merged**
